name: draw_on_path
description: A Flutter package that is used to draw text or patterm along the given path.
version: 0.0.2
repository: https://github.com/himanshugarg08/draw_on_path
homepage: https://github.com/himanshugarg08/draw_on_path

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: